---
title: "R Review - 15 Jul 19"
output: html_notebook
---
----------------------------------------------------------------

## Exercise 1 

```{r}
#### Question 1 ####

# Add 3 and 5.
Answer1 = 3+5
print("The answer is:", Answer1)
#----------------------------------------------+
#### Question 2 ####

# Subtract 67 from 666.
Answer2 = 666 - 67
print(Answer2)
#----------------------------------------------+
#### Question 3 ####

# Mutiply 555 by 444.
Answer3 = 555 * 444
print(Answer3)
#----------------------------------------------+
#### Question 4 ####

# Divide 20 by 65.
Answer4 = 20 / 65
print(Answer4)
#----------------------------------------------+
#### Question 5 ####

# Take a square root of 125.
Answer5 = sqrt(125)
print(Answer5)
#----------------------------------------------+
#### Question 6 ####

# Take a square root of a -9.

Answer6 = sqrt(-9)
print(Answer6)
# What do you get in return? Why do you think you got this as the output?

#----------------------------------------------+
#### Question 7 ####
# Raise 6 to the 10th power.
Answer7 = 6**10
print(Answer7)
#----------------------------------------------+
#### Question 8 ####

# What is the remainder when we divide 5 by 2?
Answer8 = 5%%2
print(Answer8)
```

----------------------------------------------------------------

## Exercise 2

```{r}

#### Question 1 ####

# Make a variable called `var_1` and let it be equal to a sum of 100 and 65.
# Hint: when you create a new variable, make sure you view what it is equal to 
# in console and / or environment pane.

var.1 = 100 + 65

#----------------------------------------------+
#### Question 2 ####

# Make a variable called `var_2` and let it be equal a product of 3 and 1/2.

var.2 = 3*(1/2)

#----------------------------------------------+
#### Question 3 ####

# Make a variable called `var_3`, which is a result of dividing `var_1` by `var_2`.

var.3 = var.1/var.2

#----------------------------------------------+
#### Question 4 ####

# Make a variable called `var_4` and set it equal to 110.

var.4 = 110

#----------------------------------------------+
#### Question 5 ####

# Make a variable called `temp_var` and set it equal to 10^3.

temp.var = 10^3

#----------------------------------------------+
#### Question 6 ####

# Divide it by 10 and save it to itself. What is `temp_var` now equal to?

temp.var = temp.var/10

#----------------------------------------------+
#### Question 7 ####

# Can we retrieve the initial value of `temp_var`?

#sure, by multiplying it by 10 again

#----------------------------------------------+
#### Question 8 ####

# Make a variable `Temp_Var` and assign it to the negative third power of 5.

temp.var = 5^(-3)

#----------------------------------------------+
#### Question 9 ####

# Make a variable called `007Agent` and assign this character string to it: "Bond, James Bond".
 
#cant do that yo 
OO7Agent = "Bond, James Bond"

```

----------------------------------------------------------------

## Exercise 3

```{r}
#### Question 1 ####

# Create logical variable named logvar and assign it the value FALSE.
# Using the typeof() function, confirm the type of variable for logvar.

logvar = FALSE
typeof(logvar)

#----------------------------------------------+-
#### Question 2 ####

# Convert the logical variable to a character variable named `new_char2`.
# Check the value of the new variable in the Global Environment. 
# What is the difference between logvar and new_char2?

new_char2 = as.character(logvar)
#----------------------------------------------+-
#### Question 3 ####

# Confim the class of the new variable, new_char2.

class(new_char2)
#----------------------------------------------+-
#### Question 4 ####

test = 234.3

class(test)
typeof(test)
# What is the class of the `test` variable?
# What is the type of the `test` variable?

#----------------------------------------------+-
#### Question 5 ####

# Convert `test` to an `integer` and assign it to variable `test2`.
# Then confirm the new class of `test2`.
# What is the difference in the value between `test` and `test2`?

test2 = integer(test)
class(test2)
```
----------------------------------------------------------------

## Exercise 4
```{r}
#### Question 1 ####

# Create a numeric vector named `numvec` that contains the values 2.3, 4, 5.63, and 4.623.
# Return the values of `numvec`.
numvec = c(2.3,4,5.63,4.623)
numvec
#----------------------------------------------+-
#### Question 2 ####

# Convert the vector `numvec` to a vector of integers named `intvec`.
# Then, confirm if the vector contains integers or not. 
# The answer should be either TRUE or FALSE.
intvec = as.integer(numvec)
is.integer(intvec)
#----------------------------------------------+-
#### Question 3 ####

# Check how many items are in `intvec`.
# Then, append the values 7, 14, and 8 to the vector `intvec`.
# Check the length of intvec again. What changed?

length(intvec)
intvec=c(intvec,7,14,8)
intvec 
#intvec = append(intvec,vecappend,after=4)
#intvec

length(intvec)
#----------------------------------------------+-
#### Question 4 ####

# Add the value 3 to all values in `intvec`.
intvec = intvec+3
intvec
#----------------------------------------------+-
#### Question 5 ####

# Create another vector named `seqvec` that starts at 2, ends at 14, and the numbers increase by 2.
# What is the length of `seqvec`?

seqvec = seq(2,14,2)
seqvec
#----------------------------------------------+-
#### Question 6 ####

# Assign the result of subtracting `intvec` from `seqvec` to the vector `resvec`. 
# Without looking at the `resvec`, what should be the 3rd value in `resvec`?
seqvec
intvec
resvec=seqvec-intvec
#1
resvec
#----------------------------------------------+-
#### Question 7 ####

# What is the product of resvec?
prod(resvec)
min(resvec)
mean(resvec)
# What is the minimum value in resvec?
# What is the mean of resvec?

#----------------------------------------------+-
#### Question 8 ####

# Bind the vectors `intvec`, `seqvec`, and `resvec` together as columns to create `matrix_c`.
# Separately, bind the vectors together as rows to create `matrix_r`.
# Confirm the class of both `matrix_c` and` matrix_r`.
matrix_c = cbind(intvec,seqvec,resvec)
matrix_c

matrix_r = rbind(intvec,seqvec,resvec)
matrix_r
#----------------------------------------------+-
#### Question 9 ####

# How many rows and columns are there in `matrix_c` and `matrix_r`?

#col_matrix_c = ncol(matrix_c)
#col_matrix_c
#row_matrix_c = nrow(matrix_c)
#row_matrix_c

#col_matrix_r = ncol(matrix_r)
#col_matrix_r
#row_matrix_r = nrow(matrix_r)
#row_matrix_r

dim(matrix_c)
dim(matrix_r)
#----------------------------------------------+-
#### Question 10 ####

# Check the attributes of `matrix_c`. 
attributes(matrix_c)

# Which dimension of `matrix_c` has names? Rows or columns?
# columns


# Rename the columns in `matrix_c` to be "var1", "var2", and "var3".

# colnames(data)[colnames(data)=="old_name"] <- "new_name"
#colnames(matrix_c)[colnames(matrix_c)=="intvec"]<-"var1"
#matrix_c

#colnames(matrix_c)[colnames(matrix_c)=="var3"]<-"var2"
#matrix_c

#colnames(matrix_c)[colnames(matrix_c)=="var2"]<-"var3"
#matrix_c

colnames(matrix_c)<-c("var1","var2","var3")
matrix_c
#----------------------------------------------+-
#### Question 11 ####

# Return the value in `matrix_c` that is in the 2nd column and 5th row.

matrix_c[5,2]
matrix_c
```
----------------------------------------------------------------

## Exercise 5
```{r}
#### Question 1 ####

# Convert `matrix_c` to a dataframe and name the new dataframe `matrix_df`.
# When you create the dataframe, assign the row names numbers 15:21.
# Confirm the work by checking the attributes of `matrix_df.

newdf = as.data.frame(matrix_c)
rownames(newdf) = c(15:21)
newdf 

#----------------------------------------------+-
#### Question 2 ####

# Use the three different ways to access the third column of `matrix_df`.
# Then, use the two different ways to access the fourth row.

# Method 1 - Columns
newdf$var3

# Method 2 - Columns
newdf[,3]

# Method 3 - Columns
newdf[,"var3"]

# Method 1 - Rows
newdf[4,]

# Method 2 - Rows
newdf["4",]

newdf
#----------------------------------------------+-
#### Question 3 ####

var4 = c("learning", "R", "studio", "is", "so", "much", "fun")

# Add var4 as a column to `matrix_df` using `cbind` function.

newdf = cbind(newdf,var4)
newdf
# Confirm your work using attributes.
attributes(newdf)
#----------------------------------------------+-
#### Question 4 ####

# Add var5 as a column to `matrix_df`, using the `$` operator, and set it equal to "constant".
# Again, confirm your work with attributes.
newdf$var5 = "constant"
newdf

attributes(newdf)
#----------------------------------------------+-
#### Question 5 ####

# Use `data.frame` to create a new dataframe named `new_df`, from scratch, '
new_df = data.frame(numvec,intvec,seqvec,var4,var5="constant", row.names = 23:26)
new_df

# using the vectors `numvec`, `intvec`, `seqvec,` `var4`, and `var5`. 
# Set the row names to be a sequence from 23 to 26 within the `data.frame` command.


# You will get an error.
# Why can R not join those vectors into a dataframe?

## 

#----------------------------------------------+-
#### Question 6 ####

# Use length to find the vectors that are longer than 4 entries.
length(numvec)
length(intvec)
length(seqvec)
length(var4)


new_df= data.frame(numvec, intvec[1:4], seqvec[1:4], var4[1:4], "constant", row.names = 23:26)
new_df

attributes(new_df)
str(new_df)
dim(new_df)
# Adjust the code you just wrote to use only the first four rows of the vectors that are too long.
# Remove the 'var5 =' and write only "constant".
# Check the attributes, structure, and dimensions of `new_df` to confirm your work.

#----------------------------------------------+-
#### Question 7 ####

# Create a vector named `date_vec` of four dates in %d-%b-%y format.
# The four dates should be:
# March 3, 2010
# April 4, 2011
# June 22, 2012
# September 14, 2012
# Again, they should not be in this format but rather the %d-%b-%y format.

dates = c("3 MAR 2010", "4 APR 2011", "22 JUN 2012", "13 SEP 2012")
date_vec = as.Date(dates, format = "%d %b %Y")
date_vec  


#----------------------------------------------+-
#### Question 8 ####

# Using the `$` operator, assign `date_vec` to a new column, Col6, in `new_df`.
# Make sure to use `as.Date` to ensure its format is recognized.
# Check the structure of `new_df`.

new_df$col6 = as.Date(date_vec, format = "%d %b %Y")
new_df

#----------------------------------------------+-
#### Question 9 ####

new_df$Col7 = c("lets", NA, "try", "this")
new_df
# For which row will Col7 return TRUE for using is.na?
# Use is.na to confirm.
is.na(new_df[2,])
#----------------------------------------------+-
#### Question 10 ####

# Remove Col7 from `new_df` by setting it equal to NULL.
# Confirm Col7 removal from `new_df`.

new_df$Col7 = NULL
new_df
#----------------------------------------------+-
#### Question 11 ####

# Update the column names of `new_df`, by using `colnames`, to Col1 through Col5.
colnames(new_df) = c("col1","col2","col3","col4","col5")
new_df

```

